#!/usr/bin/env bash
# Transfers a file from our client to a server

if [[ "$#" -lt 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE_PATH=$1
IP=$2
USERNAME=$3
PRIVATE_KEY_PATH=$4

scp -o StrictHostKeyChecking=no -i "${PRIVATE_KEY_PATH}"  "${FILE_PATH}" "${USERNAME}@${IP}:~/"
