#!/usr/bin/env bash
# shellcheck disable=SC2154
# Install nginx, configure it and create a redirect and error page
# and setting a custom header

apt-get update
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.*
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

CUSTOM_CONF="
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        add_header X-Served-By ${HOSTNAME};

        root /var/www/html;

	server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /var/www/html/;
                internal;
        }
}

"

echo "$CUSTOM_CONF" > /etc/nginx/sites-available/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
