#!/usr/bin/env bash
# Install and configure HAProxy

CONFIG="
frontend s1cario-frontend
	mode http
	bind :80
	default_backend s1cario-backend

backend s1cario-backend
	mode http
	balance roundrobin
	server web1 54.162.51.179:80 check
	server web2 100.25.222.165:80 check
"

apt-get update
apt-get install haproxy -y

echo "$CONFIG" >> /etc/haproxy/haproxy.cfg

/etc/init.d/haproxy restart
