#!/usr/bin/env bash
# This bash script that generates a MySQL dump and creates a compressed archive out of it.

passwd="$1"

mysqldump -u root -p "${passwd}" --all-databases -r backup.sql && \
tar -czvf "$(date +'%d-%m-%Y').tar.gz" backup.sql
