#!/usr/bin/env bash
# Script that:
#	Creates the file /var/run/myscript.pid containing its PID
#	Displays To infinity and beyond indefinitely
#	Displays I hate the kill command when receiving a SIGTERM signal
#	Displays Y U no love me?! when receiving a SIGINT signal
#	Deletes the file /var/run/myscript.pid and terminates itself
#+		when receiving a SIGQUIT or SIGTERM signal

handleINT () {
	echo "Y U no love me?!"
}

handleTERM () {
	echo "I hate the kill command"
	rmSELF
}

rmSELF () {
	rm /var/run/myscript.pid &> /dev/null
	exit
}

trap handleTERM SIGTERM
trap rmSELF SIGQUIT
trap handleINT SIGINT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done
