#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely,
#+ and handle TERM signal.

trap "echo 'I am invincible!!!'" SIGTERM

while true ; do
	echo "To infinity and beyond"
	sleep 2
done
