#!/usr/bin/env bash
# Script that displays the content of the current directory
#+ in a list format and where only the part of the name
#+ after the first dash is displayed

for file in $( ls | cut -d '-' -f 2- ); do
	echo "$file"
done
