#!/usr/bin/env bash
# Change localhost and facebook IP addresses

cp /etc/hosts ~/hosts.new

if grep -q "localhost" ~/hosts.new ; then
	LINE_NUMBER=$(grep "localhost" ~/hosts.new -n -o | cut -d':' -f 1 | head -n1)
	sed -i "${LINE_NUMBER}s/.*/127.0.0.2\tlocalhost/" ~/hosts.new
else
	echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new
fi

if grep -q "facebook.com" ~/hosts.new ; then
	echo found
	LINE_NUMBER=$(grep "facebook.com" ~/hosts.new -n -o | cut -d':' -f 1 | head -n1)
	sed -i "${LINE_NUMBER}s/.*/8.8.8.8\tfacebook\.com/" ~/hosts.new
else
	echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
fi

cp -f ~/hosts.new /etc/hosts
