#!/usr/bin/env bash
# Function to gracefully reload Gunicorn

graceful_reload() {
    if pgrep -x gunicorn &> /dev/null; then
        PID="$(pgrep -x gunicorn -o)"
        kill -HUP "$PID"
    fi
}

# Run the graceful reload function
graceful_reload
